/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as RegulationsRouteImport } from './routes/regulations'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as HelpRouteImport } from './routes/help'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditReportSessionIdRouteImport } from './routes/audit-report.$sessionId'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const RegulationsRoute = RegulationsRouteImport.update({
  id: '/regulations',
  path: '/regulations',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditReportSessionIdRoute = AuditReportSessionIdRouteImport.update({
  id: '/audit-report/$sessionId',
  path: '/audit-report/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/help': typeof HelpRoute
  '/history': typeof HistoryRoute
  '/regulations': typeof RegulationsRoute
  '/rules': typeof RulesRoute
  '/search': typeof SearchRoute
  '/audit-report/$sessionId': typeof AuditReportSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/help': typeof HelpRoute
  '/history': typeof HistoryRoute
  '/regulations': typeof RegulationsRoute
  '/rules': typeof RulesRoute
  '/search': typeof SearchRoute
  '/audit-report/$sessionId': typeof AuditReportSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/help': typeof HelpRoute
  '/history': typeof HistoryRoute
  '/regulations': typeof RegulationsRoute
  '/rules': typeof RulesRoute
  '/search': typeof SearchRoute
  '/audit-report/$sessionId': typeof AuditReportSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/help'
    | '/history'
    | '/regulations'
    | '/rules'
    | '/search'
    | '/audit-report/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/help'
    | '/history'
    | '/regulations'
    | '/rules'
    | '/search'
    | '/audit-report/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/help'
    | '/history'
    | '/regulations'
    | '/rules'
    | '/search'
    | '/audit-report/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  HelpRoute: typeof HelpRoute
  HistoryRoute: typeof HistoryRoute
  RegulationsRoute: typeof RegulationsRoute
  RulesRoute: typeof RulesRoute
  SearchRoute: typeof SearchRoute
  AuditReportSessionIdRoute: typeof AuditReportSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regulations': {
      id: '/regulations'
      path: '/regulations'
      fullPath: '/regulations'
      preLoaderRoute: typeof RegulationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-report/$sessionId': {
      id: '/audit-report/$sessionId'
      path: '/audit-report/$sessionId'
      fullPath: '/audit-report/$sessionId'
      preLoaderRoute: typeof AuditReportSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  HelpRoute: HelpRoute,
  HistoryRoute: HistoryRoute,
  RegulationsRoute: RegulationsRoute,
  RulesRoute: RulesRoute,
  SearchRoute: SearchRoute,
  AuditReportSessionIdRoute: AuditReportSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
